### ISSUE TITLE
no module 'wcmatch'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#1]
```
Python 3.8.5
Init: cuda_console_complete
Init: cuda_runner
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.on_tab_change: ModuleNotFoundError: No module named 'wcmatch'
Loaded session: "history session.json", 130ms, 0 file(s)
Startup: 290ms, plugins: 160ms (console_complete 17ms, runner 18ms, lsp 129ms)
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'wcmatch'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'wcmatch'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'wcmatch'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'wcmatch'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'wcmatch'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'wcmatch'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from wcmatch.glob import globmatch, GLOBSTAR, BRACE
ModuleNotFoundError: No module named 'wcmatch'
ERROR: Exception in CudaText for cuda_lsp.shutdown_server: ModuleNotFoundError: No module named 'wcmatch'
```

**Comment by halfbrained** [comment]
added

**Comment by Alexey-T** [comment]
не помогло.
нужно или 1) sys.path.append( plg_dir )
или 2) relative import of 'wcmatch'

**Comment by halfbrained** [comment]
I've made two commits, did you download it before the second? Works for me, event delete system install

**Comment by Alexey-T** [comment]
#2
