### ISSUE TITLE
after i changed 'from .wcmatch .....' = new error

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#2]
```
Python 3.8.5
Init: cuda_console_complete
Init: cuda_runner
Init: cuda_tab_icons
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from .wcmatch.glob import globmatch, GLOBSTAR, BRACE
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/glob.py", line 28, in <module>
    from . import _wcparse
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/_wcparse.py", line 25, in <module>
    import bracex
ModuleNotFoundError: No module named 'bracex'
ERROR: Exception in CudaText for cuda_lsp.on_open: ModuleNotFoundError: No module named 'bracex'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from .wcmatch.glob import globmatch, GLOBSTAR, BRACE
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/glob.py", line 28, in <module>
    from . import _wcparse
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/_wcparse.py", line 25, in <module>
    import bracex
ModuleNotFoundError: No module named 'bracex'
ERROR: Exception in CudaText for cuda_lsp.on_open: ModuleNotFoundError: No module named 'bracex'
Init: cuda_hilite_occurrences
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from .wcmatch.glob import globmatch, GLOBSTAR, BRACE
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/glob.py", line 28, in <module>
    from . import _wcparse
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/_wcparse.py", line 25, in <module>
    import bracex
ModuleNotFoundError: No module named 'bracex'
ERROR: Exception in CudaText for cuda_lsp.on_open: ModuleNotFoundError: No module named 'bracex'
Loaded session: "history session.json", 160ms, 3 file(s)
Startup: 320ms, plugins: 180ms (console_complete 16ms, runner 19ms, tab_icons 2ms, lsp 142ms, hilite_occurrences 5ms)
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from .wcmatch.glob import globmatch, GLOBSTAR, BRACE
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/glob.py", line 28, in <module>
    from . import _wcparse
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/_wcparse.py", line 25, in <module>
    import bracex
ModuleNotFoundError: No module named 'bracex'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'bracex'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 12, in <module>
    from .wcmatch.glob import globmatch, GLOBSTAR, BRACE
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/glob.py", line 28, in <module>
    from . import _wcparse
  File "/home/user/.config/cudatext/py/cuda_lsp/wcmatch/_wcparse.py", line 25, in <module>
    import bracex
ModuleNotFoundError: No module named 'bracex'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'bracex'
```

**Comment by halfbrained** [comment]
Seems to work now on Python 3.8

Probably will work on Python 3.6+ with a bit of tweaking.
