### ISSUE TITLE
after I fixed 'pydantic'  I got this

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#5]
```
Python 3.8.5
Init: cuda_console_complete
Init: cuda_runner
Init: cuda_tab_icons
Init: cuda_hilite_occurrences
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 19, in <module>
    from .dlg import Hint
  File "/home/user/.config/cudatext/py/cuda_lsp/dlg.py", line 6, in <module>
    from .sansio_lsp_client.structs import MarkupKind
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/__init__.py", line 3, in <module>
    from .client import *
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/client.py", line 6, in <module>
    from .pydantic import parse_obj_as, ValidationError
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/dataclasses.py", line 3, in <module>
    from .class_validators import gather_all_validators
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/class_validators.py", line 8, in <module>
    from .errors import ConfigError
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/errors.py", line 5, in <module>
    from .typing import display_as_type
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/typing.py", line 23, in <module>
    from typing_extensions import Annotated, Literal
ModuleNotFoundError: No module named 'typing_extensions'
ERROR: Exception in CudaText for cuda_lsp.on_open: ModuleNotFoundError: No module named 'typing_extensions'
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 19, in <module>
    from .dlg import Hint
  File "/home/user/.config/cudatext/py/cuda_lsp/dlg.py", line 6, in <module>
    from .sansio_lsp_client.structs import MarkupKind
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/__init__.py", line 3, in <module>
    from .client import *
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/client.py", line 6, in <module>
    from .pydantic import parse_obj_as, ValidationError
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/dataclasses.py", line 3, in <module>
    from .class_validators import gather_all_validators
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/class_validators.py", line 8, in <module>
    from .errors import ConfigError
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/errors.py", line 5, in <module>
    from .typing import display_as_type
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/typing.py", line 23, in <module>
    from typing_extensions import Annotated, Literal
ModuleNotFoundError: No module named 'typing_extensions'
ERROR: Exception in CudaText for cuda_lsp.on_tab_change: ModuleNotFoundError: No module named 'typing_extensions'
Loaded session: "history session.json", 160ms, 1 file(s)
Startup: 330ms, plugins: 190ms (console_complete 16ms, runner 19ms, tab_icons 2ms, hilite_occurrences 5ms, lsp 154ms)
Init: cuda_lsp
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 9, in <module>
    from .language import Language
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 19, in <module>
    from .dlg import Hint
  File "/home/user/.config/cudatext/py/cuda_lsp/dlg.py", line 6, in <module>
    from .sansio_lsp_client.structs import MarkupKind
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/__init__.py", line 3, in <module>
    from .client import *
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/client.py", line 6, in <module>
    from .pydantic import parse_obj_as, ValidationError
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/dataclasses.py", line 3, in <module>
    from .class_validators import gather_all_validators
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/class_validators.py", line 8, in <module>
    from .errors import ConfigError
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/errors.py", line 5, in <module>
    from .typing import display_as_type
  File "/home/user/.config/cudatext/py/cuda_lsp/sansio_lsp_client/pydantic/typing.py", line 23, in <module>
    from typing_extensions import Annotated, Literal
ModuleNotFoundError: No module named 'typing_extensions'
ERROR: Exception in CudaText for cuda_lsp.on_mouse_stop: ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by halfbrained** [comment]
yeah... trying to make it work on a VM currently
