### ISSUE TITLE
error messages for missing LSP paths

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#9]
```
Python 3.8.5
Init: cuda_console_complete
Init: cuda_runner
Init: cuda_tab_icons
Init: cuda_hilite_occurrences
Init: cuda_lsp
Loaded session: "history session.json", 120ms, 1 file(s)
Startup: 300ms, plugins: 160ms (console_complete 20ms, runner 20ms, tab_icons 3ms, hilite_occurrences 6ms, lsp 117ms)
Init: cudatext
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 205, in on_lexer
    self.on_open(ed_self)
  File "/home/user/.config/cudatext/py/cuda_lsp/lsp.py", line 163, in on_open
    if lang.on_open(doc): # doc's .lang is set only when was actually didOpen-ed
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 316, in on_open
    if self.client.is_initialized:
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 91, in client
    self._start_server()
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 116, in _start_server
    self.process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyls'
ERROR: Exception in CudaText for on_lexer: FileNotFoundError: [Errno 2] No such file or directory: 'pyls'
```

better give NOT crash but nice error msg.

**Comment by Alexey-T** [comment]
NOTE line is not colored-- coz u missed a space in "NOTE: "
![Screenshot from 2021-04-14 13-35-13](https://user-images.githubusercontent.com/4154978/114697217-4f51a180-9d26-11eb-90bf-52107574bbea.png)

**Comment by Alexey-T** [comment]
BTW, Runner start time is 19ms. maybe u can move some slow initing to func?

**Comment by Alexey-T** [comment]
and

```
NOTE:LSP: no server configs was found in "/home/user/.config/cudatext/settings"
```
not colored

**Comment by halfbrained** [comment]
fixed
